export const languageCodesArr = [
  'auto',
  'zh',
  'zh_hant',
  'yue',
  'en',
  'ja',
  'ko',
  'fr',
  'es',
  'ru',
  'de',
  'it',
  'tr',
  'pt_pt',
  'pt_br',
  'vi',
  'id',
  'th',
  'ms',
  'ar',
  'hi',
  'ml',
  'mn_cy',
  'mn_mo',
  'km',
  'nb_no',
  'nn_no',
  'fa',
  'sv',
  'pl',
  'nl',
  'uk',
  'he',
  'bg',
  'cs',
  'da',
  'et',
  'fi',
  'el',
  'hu',
  'lv',
  'lt',
  'ro',
  'sk',
  'sl',
] as const

export const languageNamesMap: Record<typeof languageCodesArr[number], { en: string, zh: string }> = {
  auto: { en: 'Auto', zh: '自动检测' },
  zh: { en: 'Chinese (Simplified)', zh: '简体中文' },
  zh_hant: { en: 'Chinese (Traditional)', zh: '繁体中文' },
  yue: { en: 'Cantonese', zh: '粤语' },
  en: { en: 'English', zh: '英语' },
  ja: { en: 'Japanese', zh: '日语' },
  ko: { en: 'Korean', zh: '韩语' },
  fr: { en: 'French', zh: '法语' },
  es: { en: 'Spanish', zh: '西班牙语' },
  ru: { en: 'Russian', zh: '俄语' },
  de: { en: 'German', zh: '德语' },
  it: { en: 'Italian', zh: '意大利语' },
  tr: { en: 'Turkish', zh: '土耳其语' },
  pt_pt: { en: 'Portuguese (Portugal)', zh: '葡萄牙语(葡萄牙)' },
  pt_br: { en: 'Portuguese (Brazil)', zh: '葡萄牙语(巴西)' },
  vi: { en: 'Vietnamese', zh: '越南语' },
  id: { en: 'Indonesian', zh: '印尼语' },
  th: { en: 'Thai', zh: '泰语' },
  ms: { en: 'Malay', zh: '马来语' },
  ar: { en: 'Arabic', zh: '阿拉伯语' },
  hi: { en: 'Hindi', zh: '印地语' },
  ml: { en: 'Malayalam', zh: '马拉雅拉姆语' },
  mn_cy: { en: 'Mongolian (Cyrillic)', zh: '蒙古语(西里尔文)' },
  mn_mo: { en: 'Mongolian (Traditional)', zh: '蒙古语(传统文字)' },
  km: { en: 'Khmer', zh: '高棉语' },
  nb_no: { en: 'Norwegian (Bokmål)', zh: '书面挪威语' },
  nn_no: { en: 'Norwegian (Nynorsk)', zh: '新挪威语' },
  fa: { en: 'Persian', zh: '波斯语' },
  sv: { en: 'Swedish', zh: '瑞典语' },
  pl: { en: 'Polish', zh: '波兰语' },
  nl: { en: 'Dutch', zh: '荷兰语' },
  uk: { en: 'Ukrainian', zh: '乌克兰语' },
  he: { en: 'Hebrew', zh: '希伯来语' },
  bg: { en: 'Bulgarian', zh: '保加利亚语' },
  cs: { en: 'Czech', zh: '捷克语' },
  da: { en: 'Danish', zh: '丹麦语' },
  et: { en: 'Estonian', zh: '爱沙尼亚语' },
  fi: { en: 'Finnish', zh: '芬兰语' },
  el: { en: 'Greek', zh: '希腊语' },
  hu: { en: 'Hungarian', zh: '匈牙利语' },
  lv: { en: 'Latvian', zh: '拉脱维亚语' },
  lt: { en: 'Lithuanian', zh: '立陶宛语' },
  ro: { en: 'Romanian', zh: '罗马尼亚语' },
  sk: { en: 'Slovak', zh: '斯洛伐克语' },
  sl: { en: 'Slovenian', zh: '斯洛文尼亚语' },
}

type FromArray<T extends readonly string[]> = Partial<Record<T[number], string>>
export type LanguagesMap = FromArray<typeof languageCodesArr>
export type LanguageCode = keyof LanguagesMap
