export const languageCodesArr = [
  'auto',
  'af',
  'sq',
  'am',
  'ar',
  'hy',
  'as',
  'az',
  'bn',
  'ba',
  'eu',
  'bs',
  'bg',
  'yue',
  'ca',
  'zh',
  'zh_hant',
  'zh-Hans',
  'hr',
  'cs',
  'da',
  'prs',
  'dv',
  'nl',
  'en',
  'et',
  'fo',
  'fj',
  'fi',
  'fr',
  'gl',
  'ka',
  'de',
  'el',
  'gu',
  'ht',
  'ha',
  'he',
  'hi',
  'mww',
  'hu',
  'is',
  'ig',
  'id',
  'iu',
  'iu-Latn',
  'ga',
  'it',
  'ja',
  'kn',
  'kk',
  'km',
  'rw',
  'tlh-Latn',
  'tlh-Piqd',
  'ko',
  'ku',
  'ky',
  'lo',
  'lv',
  'lt',
  'mk',
  'mg',
  'ms',
  'ml',
  'mt',
  'mi',
  'mr',
  'mn_cy',
  'mn-Cyrl',
  'mn_mo',
  'my',
  'ne',
  'nb',
  'nb_no',
  'nn_no',
  'or',
  'ps',
  'fa',
  'pl',
  'pt',
  'pt_pt',
  'pt_br',
  'pa',
  'otq',
  'ro',
  'ru',
  'sm',
  'sr-Cyrl',
  'sr-Latn',
  'sd',
  'si',
  'sk',
  'sl',
  'so',
  'es',
  'sv',
  'ty',
  'ta',
  'tt',
  'te',
  'th',
  'bo',
  'ti',
  'to',
  'tr',
  'tk',
  'uk',
  'hsb',
  'ur',
  'ug',
  'uz',
  'vi',
  'cy',
  'xh',
  'yo',
  'yua',
  'zu',
] as const

export const languageNamesMap: Record<typeof languageCodesArr[number], { en: string, tr: string, zh: string }> = {
  auto: { en: 'Auto', tr: 'Otomatik', zh: '自动检测' },
  af: { en: 'Afrikaans', tr: 'Afrikaanca', zh: '南非荷兰语' },
  sq: { en: 'Albanian', tr: 'Arnavutça', zh: '阿尔巴尼亚语' },
  am: { en: 'Amharic', tr: 'Amharca', zh: '阿姆哈拉语' },
  ar: { en: 'Arabic', tr: 'Arapça', zh: '阿拉伯语' },
  hy: { en: 'Armenian', tr: 'Ermenice', zh: '亚美尼亚语' },
  as: { en: 'Assamese', tr: 'Assamca', zh: '阿萨姆语' },
  az: { en: 'Azerbaijani', tr: 'Azerice', zh: '阿塞拜疆语' },
  bn: { en: 'Bengali', tr: 'Bengalce', zh: '孟加拉语' },
  ba: { en: 'Bashkir', tr: 'Başkırca', zh: '巴什基尔语' },
  eu: { en: 'Basque', tr: 'Baskça', zh: '巴斯克语' },
  bs: { en: 'Bosnian', tr: 'Boşnakça', zh: '波斯尼亚语' },
  bg: { en: 'Bulgarian', tr: 'Bulgarca', zh: '保加利亚语' },
  yue: { en: 'Cantonese', tr: 'Kantonca', zh: '粤语' },
  ca: { en: 'Catalan', tr: 'Katalanca', zh: '加泰罗尼亚语' },
  zh: { en: 'Chinese (Simplified)', tr: 'Çince (Basitleştirilmiş)', zh: '简体中文' },
  zh_hant: { en: 'Chinese (Traditional)', tr: 'Çince (Geleneksel)', zh: '繁体中文' },
  'zh-Hans': { en: 'Chinese (Simplified)', tr: 'Çince (Basitleştirilmiş)', zh: '简体中文' },
  hr: { en: 'Croatian', tr: 'Hırvatça', zh: '克罗地亚语' },
  cs: { en: 'Czech', tr: 'Çekçe', zh: '捷克语' },
  da: { en: 'Danish', tr: 'Danca', zh: '丹麦语' },
  prs: { en: 'Dari', tr: 'Darice', zh: '达里语' },
  dv: { en: 'Dhivehi', tr: 'Maldivce', zh: '迪维希语' },
  nl: { en: 'Dutch', tr: 'Hollandaca', zh: '荷兰语' },
  en: { en: 'English', tr: 'İngilizce', zh: '英语' },
  et: { en: 'Estonian', tr: 'Estonca', zh: '爱沙尼亚语' },
  fo: { en: 'Faroese', tr: 'Faroece', zh: '法罗语' },
  fj: { en: 'Fijian', tr: 'Fijice', zh: '斐济语' },
  fi: { en: 'Finnish', tr: 'Fince', zh: '芬兰语' },
  fr: { en: 'French', tr: 'Fransızca', zh: '法语' },
  gl: { en: 'Galician', tr: 'Galiçyaca', zh: '加利西亚语' },
  ka: { en: 'Georgian', tr: 'Gürcüce', zh: '格鲁吉亚语' },
  de: { en: 'German', tr: 'Almanca', zh: '德语' },
  el: { en: 'Greek', tr: 'Yunanca', zh: '希腊语' },
  gu: { en: 'Gujarati', tr: 'Guceratça', zh: '古吉拉特语' },
  ht: { en: 'Haitian Creole', tr: 'Haiti Kreyolu', zh: '海地克里奥尔语' },
  ha: { en: 'Hausa', tr: 'Hausaca', zh: '豪萨语' },
  he: { en: 'Hebrew', tr: 'İbranice', zh: '希伯来语' },
  hi: { en: 'Hindi', tr: 'Hintçe', zh: '印地语' },
  mww: { en: 'Hmong Daw', tr: 'Hmong Daw', zh: '苗族' },
  hu: { en: 'Hungarian', tr: 'Macarca', zh: '匈牙利语' },
  is: { en: 'Icelandic', tr: 'İzlandaca', zh: '冰岛语' },
  ig: { en: 'Igbo', tr: 'İbo', zh: '伊博语' },
  id: { en: 'Indonesian', tr: 'Endonezyaca', zh: '印尼语' },
  iu: { en: 'Inuktitut', tr: 'İnuktitut', zh: '因纽特语' },
  'iu-Latn': { en: 'Inuktitut (Latin)', tr: 'İnuktitut (Latin)', zh: '因纽特语（拉丁文）' },
  ga: { en: 'Irish', tr: 'İrlandaca', zh: '爱尔兰语' },
  it: { en: 'Italian', tr: 'İtalyanca', zh: '意大利语' },
  ja: { en: 'Japanese', tr: 'Japonca', zh: '日语' },
  kn: { en: 'Kannada', tr: 'Kannadaca', zh: '卡纳达语' },
  kk: { en: 'Kazakh', tr: 'Kazakça', zh: '哈萨克语' },
  km: { en: 'Khmer', tr: 'Kmerce', zh: '高棉语' },
  rw: { en: 'Kinyarwanda', tr: 'Ruandaca', zh: '卢旺达语' },
  'tlh-Latn': { en: 'Klingon (Latin)', tr: 'Klingonca (Latin)', zh: '克林贡语（拉丁文）' },
  'tlh-Piqd': { en: 'Klingon (pIqaD)', tr: 'Klingonca (pIqaD)', zh: '克林贡语（克林贡文）' },
  ko: { en: 'Korean', tr: 'Korece', zh: '韩语' },
  ku: { en: 'Kurdish', tr: 'Kürtçe', zh: '库尔德语' },
  ky: { en: 'Kyrgyz', tr: 'Kırgızca', zh: '吉尔吉斯语' },
  lo: { en: 'Lao', tr: 'Laoca', zh: '老挝语' },
  lv: { en: 'Latvian', tr: 'Letonca', zh: '拉脱维亚语' },
  lt: { en: 'Lithuanian', tr: 'Litvanca', zh: '立陶宛语' },
  mk: { en: 'Macedonian', tr: 'Makedonca', zh: '马其顿语' },
  mg: { en: 'Malagasy', tr: 'Malgaşça', zh: '马达加斯加语' },
  ms: { en: 'Malay', tr: 'Malayca', zh: '马来语' },
  ml: { en: 'Malayalam', tr: 'Malayalamca', zh: '马拉雅拉姆语' },
  mt: { en: 'Maltese', tr: 'Maltaca', zh: '马耳他语' },
  mi: { en: 'Maori', tr: 'Maorice', zh: '毛利语' },
  mr: { en: 'Marathi', tr: 'Marati', zh: '马拉地语' },
  mn_cy: { en: 'Mongolian (Cyrillic)', tr: 'Moğolca (Kiril)', zh: '蒙古语(西里尔文)' },
  'mn-Cyrl': { en: 'Mongolian (Cyrillic)', tr: 'Moğolca (Kiril)', zh: '蒙古语（西里尔文）' },
  mn_mo: { en: 'Mongolian (Traditional)', tr: 'Moğolca (Geleneksel)', zh: '蒙古语(传统文字)' },
  my: { en: 'Burmese', tr: 'Birmanca', zh: '缅甸语' },
  ne: { en: 'Nepali', tr: 'Nepalce', zh: '尼泊尔语' },
  nb: { en: 'Norwegian (Bokmål)', tr: 'Norveççe (Bokmål)', zh: '挪威语（书面挪威语）' },
  nb_no: { en: 'Norwegian (Bokmål)', tr: 'Norveççe (Bokmål)', zh: '书面挪威语' },
  nn_no: { en: 'Norwegian (Nynorsk)', tr: 'Norveççe (Nynorsk)', zh: '新挪威语' },
  or: { en: 'Oriya', tr: 'Oriya', zh: '奥利亚语' },
  ps: { en: 'Pashto', tr: 'Peştuca', zh: '普什图语' },
  fa: { en: 'Persian', tr: 'Farsça', zh: '波斯语' },
  pl: { en: 'Polish', tr: 'Lehçe', zh: '波兰语' },
  pt: { en: 'Portuguese', tr: 'Portekizce', zh: '葡萄牙语' },
  pt_pt: { en: 'Portuguese (Portugal)', tr: 'Portekizce (Portekiz)', zh: '葡萄牙语(葡萄牙)' },
  pt_br: { en: 'Portuguese (Brazil)', tr: 'Portekizce (Brezilya)', zh: '葡萄牙语(巴西)' },
  pa: { en: 'Punjabi', tr: 'Pencapça', zh: '旁遮普语' },
  otq: { en: 'Querétaro Otomi', tr: 'Querétaro Otomisi', zh: '克雷塔罗奥托米语' },
  ro: { en: 'Romanian', tr: 'Romence', zh: '罗马尼亚语' },
  ru: { en: 'Russian', tr: 'Rusça', zh: '俄语' },
  sm: { en: 'Samoan', tr: 'Samoaca', zh: '萨摩亚语' },
  'sr-Cyrl': { en: 'Serbian (Cyrillic)', tr: 'Sırpça (Kiril)', zh: '塞尔维亚语（西里尔文）' },
  'sr-Latn': { en: 'Serbian (Latin)', tr: 'Sırpça (Latin)', zh: '塞尔维亚语（拉丁文）' },
  sd: { en: 'Sindhi', tr: 'Sindhi', zh: '信德语' },
  si: { en: 'Sinhala', tr: 'Seylanca', zh: '僧伽罗语' },
  sk: { en: 'Slovak', tr: 'Slovakça', zh: '斯洛伐克语' },
  sl: { en: 'Slovenian', tr: 'Slovence', zh: '斯洛文尼亚语' },
  so: { en: 'Somali', tr: 'Somalice', zh: '索马里语' },
  es: { en: 'Spanish', tr: 'İspanyolca', zh: '西班牙语' },
  sv: { en: 'Swedish', tr: 'İsveççe', zh: '瑞典语' },
  ty: { en: 'Tahitian', tr: 'Tahitice', zh: '塔希提语' },
  ta: { en: 'Tamil', tr: 'Tamilce', zh: '泰米尔语' },
  tt: { en: 'Tatar', tr: 'Tatarca', zh: '鞑靼语' },
  te: { en: 'Telugu', tr: 'Teluguca', zh: '泰卢固语' },
  th: { en: 'Thai', tr: 'Tayca', zh: '泰语' },
  bo: { en: 'Tibetan', tr: 'Tibetçe', zh: '藏语' },
  ti: { en: 'Tigrinya', tr: 'Tigrinya', zh: '提格利尼亚语' },
  to: { en: 'Tongan', tr: 'Tongaca', zh: '汤加语' },
  tr: { en: 'Turkish', tr: 'Türkçe', zh: '土耳其语' },
  tk: { en: 'Turkmen', tr: 'Türkmence', zh: '土库曼语' },
  uk: { en: 'Ukrainian', tr: 'Ukraynaca', zh: '乌克兰语' },
  hsb: { en: 'Upper Sorbian', tr: 'Yukarı Sorbca', zh: '上索布语' },
  ur: { en: 'Urdu', tr: 'Urduca', zh: '乌尔都语' },
  ug: { en: 'Uyghur', tr: 'Uygurca', zh: '维吾尔语' },
  uz: { en: 'Uzbek', tr: 'Özbekçe', zh: '乌兹别克语' },
  vi: { en: 'Vietnamese', tr: 'Vietnamca', zh: '越南语' },
  cy: { en: 'Welsh', tr: 'Galce', zh: '威尔士语' },
  xh: { en: 'Xhosa', tr: 'Xhosa', zh: '科萨语' },
  yo: { en: 'Yoruba', tr: 'Yorubaca', zh: '约鲁巴语' },
  yua: { en: 'Yucatec Maya', tr: 'Yukatek Mayası', zh: '尤卡坦玛雅语' },
  zu: { en: 'Zulu', tr: 'Zuluca', zh: '祖鲁语' },
}

type FromArray<T extends readonly string[]> = Partial<Record<T[number], string>>
export type LanguagesMap = FromArray<typeof languageCodesArr>
export type LanguageCode = keyof LanguagesMap
