# yaml-language-server: $schema=https://www.flowlauncher.com/schemas/settings-template.schema.json
body:
  - type: dropdown
    attributes:
      name: interfaceLanguage
      label: Interface Language
      description: >
        Language for the plugin interface.
      options:
        - English
        - Türkçe
        - 简体中文
      defaultValue: English

  - type: textarea
    attributes:
      name: services
      label: Translate Services
      description: >
        Translation services, one per line.

        Supported services:

        Without configuration:

        Youdao, Google, Baidu, Bing, DeepL, DeepLX

        Tencent, Transmart, Caiyun, Volcegine

        Requires configuration:

        DeepLX, MTranServer

      defaultValue: "youdao\ndeepl\ngoogle\nbing"

  - type: textarea
    attributes:
      name: serviceConfigs
      label: Service Configs
      description: >
        Config services that require configuration

        e.g. DeepLX, MTranServer

        DEEPLX_URL=xxxx

        MTRANSERVER_URL=xxxx

        MTRANSERVER_TOKEN=xxxx

      defaultValue: ''

  - type: input
    attributes:
      name: proxyUrl
      label: Proxy URL
      description: >
        Proxy server URL for requests.

        Example: http://127.0.0.1:7890
      defaultValue: ''

  - type: input
    attributes:
      name: requestTimeout
      label: Request Timeout
      description: >
        Request timeout in milliseconds.

        Requests exceeding this time will be aborted.
      defaultValue: '3000'

  - type: input
    attributes:
      name: sourceLanguageCode
      label: Source Language Code
      description: >
        Source language code.

        Use 'auto' for automatic detection.
      defaultValue: auto

  - type: input
    attributes:
      name: targetLanguageCode
      label: Target Language Code
      description: >
        Target language code.

        See plugin repository for language codes.
      defaultValue: en

  - type: textarea
    attributes:
      name: languagePairs
      label: Language Pairs
      description: >
        Pre-configured language pairs, one per line.

        These will be shown as quick options.

        Example: en>zh
      defaultValue: ''

  - type: input
    attributes:
      name: triggerKeyword
      label: Trigger Keyword
      description: >
        Keyword you set to trigger this plugin.

        Required when you need language pairs.
      defaultValue: tr
